// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Divider: typeof import('./components/Divider.vue')['default']
    InputText: typeof import('./components/InputText.vue')['default']
    ModalError: typeof import('./components/ModalError.vue')['default']
    ModalProjectInput: typeof import('./components/ModalProjectInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableProjectLists: typeof import('./components/TableProjectLists.vue')['default']
    TableTd: typeof import('./components/TableTd.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
  }
}
